### ISSUE TITLE
Save model

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [SleipRecx/tfidf-search#1]
How do you save the model created by 

`model = IR(paragraphs, stop_words, True)`

to a file to be later loaded and used with  `model.lsi_query` and `model.tfidf_query`?

**Comment by SleipRecx** [comment]
In order to save the model you have to serialize and save `self.dictionary; self.tfidf_model; self.tfidf_similarity; self.lsi_model; self.lsi_similarity` These are all gensim objects and documentation on how to save and load them can be found [here.](https://radimrehurek.com/gensim/corpora/dictionary.html)

**Comment by ErfolgreichCharismatisch** [comment]
Good.

I wrote

```
model = IR(paragraphs, stop_words, True)
model.dictionary.save('dictionary.mod')
model.tfidf_model.save('tfidf_model.mod')
model.tfidf_similarity.save('tfidf_similarity.mod');
model.lsi_model.save('lsi_model.mod')
model.lsi_similarity.save('lsi_similarity.mod')
```

and to restore I wrote

```
paragraphs = ['Test','Test']
stop_words = ['Test','Test']
model = IR(paragraphs, stop_words, True)
model.dictionary.load('dictionary.mod')
model.tfidf_model.load('tfidf_model.mod')
model.tfidf_similarity.load('tfidf_similarity.mod');
model.lsi_model.load('lsi_model.mod')
model.lsi_similarity.load('lsi_similarity.mod')
```

Yet it does not replace the given dummy paragraphs with the ones of the model.

What is the cause and how do I fix it?

**Comment by ErfolgreichCharismatisch** [comment]
Push

**Comment by SleipRecx** [comment]
I'm not sure, try looking at the documentation I provided. I'm closing this issue because it's not relevant to my code.
